name: mae_medium
model:
  _target_: model_training.models.spectral_gpt.spectral_gpt.MaskedAutoencoderViT
  img_size: 500
  num_channels: 1
  num_wavelengths: 30
  spatial_patch_size: 25
  wavelength_patch_size: 5

  encoder_embed_dim: 512
  encoder_depth: 16
  encoder_num_heads: 16

  decoder_embed_dim: 256
  decoder_depth: 8
  decoder_num_heads: 8

  mlp_ratio: 4
  mask_ratio: 0.8
