# Complete preset configuration for 240x240 training

defaults:
  - /config
  - override /model: mae_medium_240
  - override /dataset: dataset_240
  - override /augmentation: transform_240

# Optimized hyperparameters for 240x240 images
hparams:
  batch_size: 4  # Can use larger batch with smaller images
  nb_epochs: 250
  lr: 0.0001

# Trial mode for quick testing
dataset:
  trial_mode: false