use_transform: true
transform:
    - hflip:
        _target_: eitorch.transform.paired_transform.HorizontalFlipTransform
        probability: 0.5
    - vshift:
        _target_: eitorch.transform.paired_transform.VerticalShiftTransform
        shift_jitter: 72  # Scaled: 150 * (240/500) = 72
    - hshift:
        _target_: eitorch.transform.paired_transform.HorizontalShiftTransform
        shift_jitter: 72  # Scaled: 150 * (240/500) = 72
    - gauss:
        _target_: eitorch.transform.paired_transform.GaussianTransform
        gauss_jitter: 0.8  # Keep same - intensity-based
    - rotate:
        _target_: eitorch.transform.paired_transform.RotateTransform
        rotate_jitter: 30  # Keep same - angle-based
#    - noise:
#        _target_: eitorch.transform.paired_transform.NoiseTransform
#        intensity_jitter: 0.1
    - scale:
        _target_: eitorch.transform.paired_transform.ScaleTransform
        scale_jitter: 0.5  # Keep same - relative scaling